name: Tests

on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.os-name }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os-name: Windows
            target: x86_64-pc-windows-msvc

#           - os: ubuntu-latest
#             os-name: Linux
#             target: x86_64-unknown-linux-gnu
# 
#           - os: macos-latest
#             os-name: macOS
#             target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."
          key: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libxext-dev \
            libxrender-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libwayland-dev \
            libxkbcommon-dev \
            pkg-config

      - name: Check (cargo check)
        run: cargo check --target ${{ matrix.target }}

      - name: Clippy
        run: cargo clippy --target ${{ matrix.target }}

      - name: Run Tests
        run: cargo test --target ${{ matrix.target }} --verbose
